### ISSUE TITLE
Should we separate commands? (Mardatonne v2 reference)

### ISSUE THREAD

**Issue by PCTipsGR** [NeotiDev/discord.js-sample-bot#3]
Since we separated commands and put each one on their own folder on Mardatonne, I wondered whether it would be a nice idea to do the same thing to this sample bot.

My opinion is that it would help new discord.js developers customize their bot more easily and it would make it faster as well.

**Comment by yagizhan49** [comment]
Why not :^)

**Comment by yagizhan49** [comment]
Already done :)

**Comment by PCTipsGR** [comment]
Thanks!
